name: Build and Test .NET Framework 4.6.1 Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.6.1'

    - name: Restore dependencies
      run: nuget restore WPFAPP.sln

    - name: Build
      run: msbuild /p:Configuration=Release WPFAPP.sln
